site_name: Licenses

nav:
  - Головна: index.md

theme:
  name: material
  language: uk
  features:
    - search.suggest
    - search.highlight
    - search.share

plugins:
  - search:
      lang:
        - ru
        - en
      separator: '[\s\-\.]+'
      prebuild_index: true

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - def_list