site_name: Licenses

nav:
  - Головна: index.md

theme:
  name: material
  language: uk
  features:
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate

plugins:
  - search:
      lang:
        - ru
        - en
      separator: '[\s\-\.]+'
      prebuild_index: true
  - mkdocstrings

markdown_extensions:
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list